version: '3'
services:
  redis:
    image: redis
    restart: always

  index:
    build: index
    restart: always
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379/
    depends_on:
      - redis

  api:
    build: api
    restart: always
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379/
    ports:
      - "9000:9000"
    depends_on:
      - index
