version: '3'
services:
  rabbit:
    image: rabbitmq:management
    restart: always
    hostname: robodex-rabbit
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=robodex
      - RABBITMQ_DEFAULT_PASS=bEE2VWehu7JI0f3N

  redis:
    image: redis
    restart: always

  index:
    build: index
    restart: always
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379/
    depends_on:
      - redis

  api:
    build: api
    restart: always
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379/
      - RABBIT_URL=amqp://robodex:bEE2VWehu7JI0f3N@rabbit
    ports:
      - "9000:9000"
    depends_on:
      - index

  core:
    build: core
    restart: always
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379/
    depends_on:
      - redis
      - index
      