version: '3'
services:
  nginx:
    build: nginx
    restart: always
    ports:
      - "80:80"

  landing:
    build: ../robodex-landing
    restart: always

  api:
    build: api
    restart: always
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379/
    depends_on:
      - index

  udf:
    build: udf
    restart: always
    environment:
      - NODE_ENV=production

  web:
    build: ../robodex-react
    restart: always
    depends_on:
      - api
      - udf

  redis:
    image: redis
    restart: always

  index:
    build: index
    restart: always
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379/
    depends_on:
      - redis
