version: '3'
services:
  nginx:
    build: nginx
    restart: always
    ports:
      - "80:80"

  landing:
    build: ../robodex-landing
    restart: always

  api:
    build: api
    restart: always

  udf:
    build: udf
    restart: always
    environments:
      - NODE_ENV=production

  web:
    build: ../robodex-react
    restart: always
