version: '3'
services:
  nginx:
    build: nginx
    restart: always
    ports:
      - "80:80"

  landing:
    build: ../robodex-landing
    restart: always

  api:
    build: api
    restart: always
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379/
      - RABBIT_URL=amqp://robodex:bEE2VWehu7JI0f3N@rabbit
    depends_on:
      - index
      - rabbit

  udf:
    build: udf
    restart: always
    environment:
      - NODE_ENV=production

  web:
    build: ../robodex-react
    restart: always
    depends_on:
      - api
      - udf

  rabbit:
    image: rabbitmq:management
    restart: always
    hostname: robodex-rabbit
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=robodex
      - RABBITMQ_DEFAULT_PASS=bEE2VWehu7JI0f3N

  redis:
    image: redis
    restart: always

  index:
    build: index
    restart: always
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379/
    depends_on:
      - redis
